version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 99
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
    time: "06:10"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 99
