kind: pipeline
type: docker
name: goodwe2pvoutput

steps:
- name: testbuild
  image: python:3.7
  commands:
  - pip install -r requirements.txt
  - pip install .
  - python setup.py sdist bdist_wheel 
