[env]
_.file = { path = ".envrc", redact = true, required = true }

[tools]
opentofu = "latest"
shellcheck = "latest"
uv = "latest"

[tasks.tofu-validate]
run = ["tofu validate"]

[tasks.ruff]
run = ["uv run ruff check"]

[tasks.ty]
run = ["uv run ty check"]

[tasks.pytest]
run = ["uv run pytest"]

[tasks.check]
depends = ["tofu-validate", "ruff", "ty", "pytest"]

[tasks.coverage]
run = [
    "uv run coverage run -m pytest",
    "uv run coverage xml",
    "uv run coveralls",
]
